language: cpp
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-add-repository -y ppa:comp-phys/stable
  - sudo add-apt-repository -y ppa:boost-latest/ppa
  - sudo add-apt-repository -y "deb http://us.archive.ubuntu.com/ubuntu trusty main universe"
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-4.8 libarmadillo-dev libarmadillo4 libboost1.54-all-dev
  - export CC=gcc-4.8
  - export CXX=g++-4.8
  - printenv
  - sudo cp .travis/config.hpp /usr/include/armadillo_bits/config.hpp
  - sudo apt-get install ruby lcov
  - sudo gem install coveralls-lcov
install:
  - mkdir build && cd build && cmake -DBUILD_WITH_COVERAGE=ON .. && make -j4
script:
  - travis_wait 30 ./mlpack_coverage -g gcov-4.8
after_success:
  - coveralls-lcov .coverage.total
notifications:
  email:
    - mlpack-git@cc.gatech.edu
  irc:
    - "chat.freenode.net#mlpack"
