sudo: required
language: cpp

matrix:
  include:
    - name: xenial-python2
      os: linux
      dist: xenial
      env: CMAKE_OPTIONS="-DDEBUG=OFF -DPROFILE=OFF -DPYTHON=/usr/bin/python"
      before_install:
        - sudo apt-get update
        - sudo apt-get install -y --allow-unauthenticated libopenblas-dev liblapack-dev g++ libboost-all-dev python-pip cython python-numpy python-pandas
        - sudo pip install --upgrade --ignore-installed setuptools
        - curl https://ftp.fau.de/macports/distfiles/armadillo/armadillo-6.500.5.tar.gz | tar xvz && cd armadillo*
        - cmake . && make && sudo make install && cd ..
        - sudo cp .travis/config.hpp /usr/include/armadillo_bits/config.hpp

    - name: xenial-python3
      os: linux
      dist: xenial
      env: CMAKE_OPTIONS="-DDEBUG=OFF -DPROFILE=OFF -DPYTHON=/usr/bin/python3"
      before_install:
        - sudo apt-get update
        - sudo apt-get install -y --allow-unauthenticated libopenblas-dev liblapack-dev g++ libboost-all-dev python3-pip cython3 python3-numpy python3-pandas
        - sudo pip3 install --upgrade --ignore-installed setuptools
        - curl https://ftp.fau.de/macports/distfiles/armadillo/armadillo-6.500.5.tar.gz | tar xvz && cd armadillo*
        - cmake . && make && sudo make install && cd ..
        - sudo cp .travis/config.hpp /usr/include/armadillo_bits/config.hpp

    - name: xenial-debug
      os: linux
      dist: xenial
      env: CMAKE_OPTIONS="-DDEBUG=ON -DPROFILE=OFF -DBUILD_PYTHON_BINDINGS=OFF"
      before_install:
        - sudo apt-get update
        - sudo apt-get install -y --allow-unauthenticated libopenblas-dev liblapack-dev g++ libboost-all-dev
        - curl https://ftp.fau.de/macports/distfiles/armadillo/armadillo-6.500.5.tar.gz | tar xvz && cd armadillo*
        - cmake . && make && sudo make install && cd ..
        - sudo cp .travis/config.hpp /usr/include/armadillo_bits/config.hpp

    - name: xenial-icc
      os: linux
      dist: xenial
      env:
        global:
          - secure: YO9kOZQ2xxDeZs801ZBo22aRv5UXNGenp9O5imlMDQpz3kPosGuAqPOYAGuk1MjmodTpNIHrQIrF1ab6CaF0VcWI+C+XWBgu1hUSVMRArZTI13ezx5DDN4XUjWZQ4MWtdINXk4EVa38/HRwJBf7dO3wjYLzZHzp48uWrBhy6W4w=
          - CMAKE_OPTIONS="-DDEBUG=ON -DPROFILE=OFF -DBUILD_PYTHON_BINDINGS=OFF"
      before_install:
        - curl https://raw.githubusercontent.com/nemequ/icc-travis/master/install-icc.sh > install-icc.sh
        - chmod +x ./install-icc.sh
        - ./install-icc.sh
        - curl https://ftp.fau.de/macports/distfiles/armadillo/armadillo-6.500.5.tar.gz | tar xvz && cd armadillo*
        - cmake . && make && sudo make install && cd ..
        - sudo cp .travis/config.hpp /usr/include/armadillo_bits/config.hpp

    - name: osx
      os: osx
      osx_image: xcode9.4 # Maybe we can try some different ones?
      env: CMAKE_OPTIONS="-DDEBUG=ON -DPROFILE=OFF -DBUILD_PYTHON_BINDINGS=OFF"
      before_install:
        - brew install openblas armadillo || brew install openblas armadillo

install:
  - mkdir build && cd build && cmake $CMAKE_OPTIONS .. && travis_wait 60 make -j2

script:
  - CTEST_OUTPUT_ON_FAILURE=1 travis_wait 30 ctest -j2

notifications:
  email:
    - mlpack-git@lists.mlpack.org
  irc:
    channels:
      - "chat.freenode.net#mlpack"
    on_success: change
    on_failure: always
